### ISSUE TITLE
Update to the webcam links for the Palomar telescopes 

### ISSUE THREAD

**Issue by rswalters** [fritz-marshal/fritz-beta-feedback#1]
Very small detail but the webcam to the Palomar telescopes should point to
http://algol.palomar.caltech.edu/instruments/allsky/AllSkyCurrentImage.JPG for night time sky conditions.  And fwiw there also the inside the dome cam and the view from High Point which looks down on the all the Palomar telescopes
http://nera.palomar.caltech.edu/upload/p48/p48-webcam-latest_1.jpg

http://hpwren.ucsd.edu/cameras/L/hp-w-mobo-c.jpg

**Comment by dannygoldstein** [comment]
fixed
