### ISSUE TITLE
Problems with finder chart generator

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#10]
Hi,

This is the output for ZTF18acenqto.

Cheers,

Steve

[finder_ZTF18acenqto.pdf](https://github.com/fritz-marshal/fritz-beta-feedback/files/5407313/finder_ZTF18acenqto.pdf)

**Comment by dannygoldstein** [comment]
Fixed in skyportal/skyportal#1084
