### ISSUE TITLE
Increase the size of the spectroscopic plot

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#100]
Hi,

Thanks for adding additional lines to the spec tool. The new physical size of the plot window shrunk. It should have the same size as the plot of the light curve plot.

**Comment by guynir42** [comment]
It may also be useful to make the accordion a bit taller to allow using the controls on the bottom without scrolling.

**Comment by mcoughlin** [comment]
Closing and opening on SkyPortal: https://github.com/skyportal/skyportal/issues/3126
