### ISSUE TITLE
Reduce white space in comment box

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#102]
Hi,

The margins of the comment box are different from the auto-annotations (Screenshot attached). It would be good to have the same margins.

Cheers,

Steve

![Screenshot 2021-05-24 at 09 23 53](https://user-images.githubusercontent.com/11585543/119311863-e12bc300-bc71-11eb-9f1b-195adaa9964a.png)

**Comment by dmitryduev** [comment]
Implemented, closing.
