### ISSUE TITLE
Add redshift provenance to redshifts

### ISSUE THREAD

**Issue by scizen9** [fritz-marshal/fritz-beta-feedback#104]
**Feature Summary**
Add provenance items to redshift records.  This could begin with a simple type: ['host-spectrum', 'transient-spectrum', 'transient-ML-fit', 'NED', ...].  Then add more detailed source information: instrument, spectrum, etc.  In addition, add more complex error limits, when appropriate.

**Usage / behavior**
These items would appear in the database and be displayed on the front-end in the redshift history records.

**Implementation details**
This will require adding columns to the redshift table and updating the redshift history front-end display.

**Context**
This will improve the usability of redshifts on Fritz.

**Comment by guynir42** [comment]
Maybe add `origin` column to the redshift table?

**Comment by guynir42** [comment]
Data model implemented by SP#2772
