### ISSUE TITLE
Download Spectrum with Header Information

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#106]
**Feature Summary**
When downloading a spectrum manually from Fritz (i.e Manage Data tab) we would like for the file to also contain the spectrum header if it contains any. Currently, the spectrum that is downloaded is a .csv file that only contains the spectrum data (i.e wavelength and flux).

**Usage / behavior**
The download file should either be a .txt file or .ascii file that also contains the header information that is uploaded

Thanks! 🚀

**Comment by dannygoldstein** [comment]
For now you can get this from the API, 

https://fritz.science/api/spectrum/123

Then index the json key with `'original_file_string'`

**Comment by mcoughlin** [comment]
Closing and opening on SkyPortal: https://github.com/skyportal/skyportal/issues/3121
