### ISSUE TITLE
Display full accuracy H0 for cosmology

### ISSUE THREAD

**Issue by tawnysit** [fritz-marshal/fritz-beta-feedback#107]
Hello,

We have noticed that there is a small inconsistency in the cosmological parameters in the About page on Fritz. The current parameters on the page are `FlatLambdaCDM(name=“Planck18_arXiv_v2”, H0=67.7 km / (Mpc s), Om0=0.31, Tcmb0=2.725 K, Neff=3.05, m_nu=[0. 0. 0.06] eV, Ob0=0.049).`

However, if you look at the astropy [`parameters.py`,](https://github.com/astropy/astropy/blob/a3263b683cf91747c062dafe31af994b2848f696/astropy/cosmology/parameters.py#L80) the Planck18_v2 has H0=67.66 km/(Mpc s).

For any source (on the source page, for example: ZTF21abfugtx) it is clear that the luminosity distance being used is **H0=67.66** and not H0=67.7 (as stated on the Fritz about page).

Would it please be possible to update the About page to reflect that H0=67.66 km/(Mps s) that is currently being used to estimate the distance?

Current version: v0.9.dev0+git20210617.fbd9aec+fritz.c76e20c

-Tawny and Andy

**Comment by stefanv** [comment]
Here is what I see in my terminal, and what you also see on the website:

```ipython
In [3]: from astropy import cosmology

In [4]: cosmology.Planck18_arXiv_v2
Out[4]: FlatLambdaCDM(name="Planck18_arXiv_v2", H0=67.7 km / (Mpc s), Om0=0.31, Tcmb0=2.725 K, Neff=3.05, m_nu=[0.   0.   0.06] eV, Ob0=0.049)
```

So, it looks like, by default, cosmology prints out to 3 digits only.

**Comment by stefanv** [comment]
Here's their (astropy's) print string:

```
    def __repr__(self):
        retstr = "{0}H0={1:.3g}, Om0={2:.3g}, Tcmb0={3:.4g}, "\
                 "Neff={4:.3g}, m_nu={5}, Ob0={6:s})"
        return retstr.format(self._namelead(), self._H0, self._Om0,
                             self._Tcmb0, self._Neff, self.m_nu,
                             _float_or_none(self._Ob0))
```

**Comment by stefanv** [comment]
I've updated the title to reflect the problem; i.e., that we could display the cosmology differently from the astropy default.

```
In [6]: cosmology.Planck18_arXiv_v2
Out[6]: FlatLambdaCDM(name="Planck18_arXiv_v2", H0=67.7 km / (Mpc s), Om0=0.31, Tcmb0=2.725 K, Neff=3.05, m_nu=[0.   0.   0.06] eV, Ob0=0.049)

In [7]: cosmology.Planck18_arXiv_v2.H0
Out[7]: <Quantity 67.66 km / (Mpc s)>
```

Note that H0 is 67.66, but the printout is 67.7 (rounded).

**Comment by acrellin** [comment]
Yes, this is more an issue with astropy than with Fritz. We're simply reporting what astropy outputs verbatim.

**Comment by acrellin** [comment]
And 67.7 is the correct value, in fact -- just to 3 sig figs

**Comment by stefanv** [comment]
We can probably override the display to give more accuracy there; I understand why it would be confusing if you entered that H0 value into a simulation, e.g..

**Comment by mcoughlin** [comment]
Closing and opening here: https://github.com/skyportal/skyportal/issues/3136
