### ISSUE TITLE
Binning & Smoothing Spectra on Fritz

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#109]
It has come to our attention that the binning resolution of the spectra being uploaded on Fritz is being displayed at a high resolution and generally are lacking smoothing. This has particularly has made it challenging to identify spectroscopic features and classify our spectra.

**Feature Summary**
We would like to request a feature that would allow the user to bin the spectra for a given binning factor. Ideally, this feature would be similar to the binning factor used on the GROWTH marshal (see examples below). 

<img width="622" alt="Screen Shot 2021-07-20 at 11 51 26 AM" src="https://user-images.githubusercontent.com/22720676/126379432-b9645e6d-ace5-4116-8003-449d0d6e291b.png">

<img width="634" alt="Screen Shot 2021-07-20 at 11 51 19 AM" src="https://user-images.githubusercontent.com/22720676/126379429-c7c44764-102a-4046-bc66-ad598b54519d.png">

**Usage / behavior**
Similar to the screenshots above, we would like to have a toolbar where the user can select a binning factor applied to the displayed spectrum on Fritz. 

Thank you in advance! 🚀

**Comment by guynir42** [comment]
Closed by #2486
