### ISSUE TITLE
Lightcurve of ZTF18acenqto is incorrect

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#11]
Hi,

I manually added ZTF18acenqto to Fritz. ZTF18acenqto has ZTF measurements starting from December 2018. These measurements are not shown. Instead, the light curve shows photometry from the past 50 days. The SLSN is too faint to be detected by ZTF.

Cheers,

Steve

![Screenshot from 2020-10-20 11-27-33](https://user-images.githubusercontent.com/11585543/96560678-44faa180-12c7-11eb-8075-08d2b6453b90.png)

**Comment by dmitryduev** [comment]
Fixed in [#14](https://github.com/dmitryduev/kowalski/pull/14) on Kowalski.

**Comment by dmitryduev** [comment]
+ the beta-testing instance only has the alerts going back to mid-September

**Comment by steveschulze** [comment]
Hmm, the ZTF-I Marshal doesn't show the data that are on Fritz. The light curve on Fritz is also very different from how the transient looks like.

Cheers,

Steve

<img width="622" alt="Screenshot 2020-10-20 at 20 35 00" src="https://user-images.githubusercontent.com/11585543/96623434-0dfead00-1314-11eb-856d-c637f0af34da.png">
