### ISSUE TITLE
Sign-in alternative to Google

### ISSUE THREAD

**Issue by simeonreusch** [fritz-marshal/fritz-beta-feedback#110]
**Feature Summary**
There should be a auth database hosted at Caltech. I try to avoid Google services as much as possible (as soon as you are signed in somewhere you are exposed to cross-site tracking) and would very much prefer an authentication using a local database (which is implementable via PSA, as @stefanv pointed out).

**Usage / behavior**
The "sign in via Google" should be complemented with "sign in at Caltech".

**Comment by stefanv** [comment]
@dima This requires assistance from the Caltech IT department. Do we have a contact there? You can send it to me privately.

**Comment by dannygoldstein** [comment]
We have had a pretty good  experience with auth0: https://auth0.com/. 

They allow SSO via github.

Here is the react single page app SDK: https://github.com/auth0/auth0-react

**Comment by stefanv** [comment]
We used auth0 for a while, but we decided to opt for an open system with more backends.

**Comment by mcoughlin** [comment]
Closing and opening here: https://github.com/skyportal/skyportal/issues/3135
