### ISSUE TITLE
Replacing usernames by real names

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#112]
Hi,

There is no clear convention on how people define their user names. E.g. myself - steve-schulze, Jesper Sollerman - jesper, Erik Kool - ekool. If I want to ping someone on Fritz, I usually have to guess what the username might be and hope it works.

It would be highly desirable if real names are used or if Fritz allows usernames as well as real names to ping people.

Cheers,

Steve

**Comment by acrellin** [comment]
This is addressed by https://github.com/skyportal/skyportal/pull/2464 which implements auto-completion of user mentions in comments, matching on any of username, first name, or last name.
