### ISSUE TITLE
Sorting doesn't always work 

### ISSUE THREAD

**Issue by idoirani** [fritz-marshal/fritz-beta-feedback#114]
Description: 
When sorting using the drop menu from the "Annotation Sorting" section, the sorting doesn't work. However, when pressing on the icon directly above the objects, the sorting works. (in the picture, 1 doesn't work, 2 does work). 

screenshot: 
![issue_fritz](https://user-images.githubusercontent.com/43962165/135758883-cc2e1def-6fa9-4551-910f-90b5db678339.png)

 - Fritz version: v0.9.dev0+git20210915.d4f3600+fritz.815dd14
 - Browser: chrome, both on my desktop and phone

**Comment by mcoughlin** [comment]
Closing and opening on SkyPortal: https://github.com/skyportal/skyportal/issues/3127
