### ISSUE TITLE
Give allocations names and do not take name from group

### ISSUE THREAD

**Issue by scizen9** [fritz-marshal/fritz-beta-feedback#115]
The current allocation system is very unwieldy because of the nature of fritz groups.

For example, this round we have two BTS programs, one for Caltech and one for ZTF.  In order to track the allocations and their time spent, we need a unique programname in the request sent to SEDM.  That programname is currently mapped to the group name associated with the allocation.  The two BTS programs should use the same group on fritz so that the BTS team can send requests under either allocation.

The fix for this is to add a field "programname" to the allocations table and to allow multiple allocations to use the same group.  This requires a front-end mod to take the allocations in the followup drop-down from the allocations table instead of from the group name.

For the particular case here, we would have two allocations: "BTS ZTF" and "BTS Caltech" that would both use the same group (41) but have unique program names so SEDM can keep track of usage by these different programs.

**Comment by scizen9** [comment]
I addition, this would allow a new set of allocations every new semester and the names should have the semester in them.  This would also require that multiple allocations use the same group number.

**Comment by dmitryduev** [comment]
We use a one-to-many mapping (Group -> Allocations). Allocations have the [proposal_id](https://github.com/skyportal/skyportal/blob/master/skyportal/models.py#L1790) column that you can make non-nullable, unique and required - and use that wherever you need on the front-end/your SEDM side.

**Comment by mcoughlin** [comment]
@scizen9 Looking at @dmitryduev's explanation, I agree with this. proposal_id is basically the name. Let us know if this is insufficient in the end.
