### ISSUE TITLE
Missing ZTF thumbnails

### ISSUE THREAD

**Issue by Yashvi-Sharma** [fritz-marshal/fritz-beta-feedback#116]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
Some sources have missing ZTF thumbnails on scanning and source pages but there are new photometry points in light curves (eg. https://fritz.science/source/ZTF18aaqkywr). The thumbnails are there on the alerts page but look like bad subtractions. Sources for which this is happening have old ZTF names from some spurious detections in their history.

**To Reproduce**
1. Go to https://fritz.science/source/ZTF18aaqkywr
2. Scroll down to thumbnails (missing)
3. Click on 'Search ZTF alert archives'
4. Thumbnails are present

**Expected behavior**
Thumbnails should not be missing in the scanning page (candidates) when new photometry is visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/26347304/161599390-d5e10087-78df-4ac5-8449-0f88592b05db.png)

**Platform information:**
 - Fritz version:  Fritz v0.9.dev0+git20220325.425410d4+fritz.d40466b.
 - Browser
   - [ Firefox] I'm browsing on a desktop

**Comment by mcoughlin** [comment]
Closing and opening on fritz: https://github.com/fritz-marshal/fritz-beta-feedback/issues/116
