### ISSUE TITLE
UI in observing runs list can lead to accidental deletion

### ISSUE THREAD

**Issue by ebellm** [fritz-marshal/fritz-beta-feedback#117]
**Describe the bug**

In the [observing runs page](https://fritz.science/runs), the active button area to delete the run ("X") overlaps the "More Info" button area.  Mis-clicking on the X immediately deletes the run and all of its contents without confirmation.

**To Reproduce**
1. Go to https://fritz.science/runs
2. Hover over the 'X', and over the 'More Info'
3. Observe that they overlap

**Expected behavior**

It would be preferable for the "delete run" option to have a confirmation option, or at least be more distinctly separated from "More Info."  Making the observing run name clickable would also decrease mis-clicks.

**Screenshots**

![Screen Shot 2022-05-31 at 4 18 58 PM](https://user-images.githubusercontent.com/733983/171299312-77ffb690-9c6d-4378-93c5-28c08b8b593d.png)

**Platform information:**
 - Fritz version:  v0.9.dev0+git20220526.28383167+fritz.d3ec874
 - Browser: Firefox and Chrome
   - [X] I'm browsing on a desktop
   - [ ] I'm browsing on my phone

**Comment by mcoughlin** [comment]
Looks like this got fixed! Let us know if further issues @ebellm
