### ISSUE TITLE
Feature requests: spectroscopy

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#12]
Hi,

The lines of the spectra appear to be non-solid. Could you show them as solid lines?

It would be important/critical to have the following features like on the old Marshal:
-rebin spectra
-overlay telluric lines
-overlay typical galaxy lines (absorption and emission)
-add lines from WN/WC/WO stars; critical for infant SN studies
-define the velocity of each spectral feature; SN features will not have the same velocity
-blank fields to add customised lines
-display which lines are shown when you hover over the element
-add comments to individual spectra. should also be shown next to the spectrum

Cheers,

Steve

![Screenshot from 2020-10-20 11-58-08](https://user-images.githubusercontent.com/11585543/96564312-ab81be80-12cb-11eb-88d0-a6616bd36c9a.png)

**Comment by AndyTza** [comment]
I will also add that currently on frirz the spectra line features are not working.

**Comment by dannygoldstein** [comment]
This is what we currently have: 

![Screen Shot 2020-11-02 at 2.18.58 PM.png](https://images.zenhubusercontent.com/59e2c99cb0222d5de47baddd/5262bd38-899b-4078-be76-a3abada54bcb)

**Comment by steveschulze** [comment]
Thanks Danny. This is already very good. The suggestions would be extremely useful and important for the observers.

**Comment by scizen9** [comment]
The color pallette for the spectra includes yellow as the second item, which is unfortunate as it is not very visible.  Is there any way to put yellow much further down the list of colors?

**Comment by dannygoldstein** [comment]
@steveschulze Can you send over the lines you want shown ?

**Comment by steveschulze** [comment]
Hi @dannygoldstein, we are compiling a line list.

Another thing. When I set the line velocity by a numerical value, I need to leave the velocity field first before the new value is applied. It would be better if a change is applied immediately without the need of leaving the field.

**Comment by stefanv** [comment]
@dannygoldstein I know you've closed some of these items recently. Can you please split remaining issues into separate tickets? Thanks!

**Comment by steveschulze** [comment]
Weizmann prepared a list of lines and feature groups that would we would like to see on Fritz.

```
H 3970,4102,4341,4861,6563, 10052,10941,12822,18756

HeI 3889,4471, 5876,6678,7065
HeII 3203,4686,5411,6560,6683,6891,8237,10124

CII 3919,3921,4267,5145,5890,6578,7231,7236,9234,9891
CIII 4647,4650,5696,6742,8500,8665,9711
CIV 4658,5801,5812,7061,7726,8859

NII 3995,4631,5005,5680,5942,6482,6611
NIII 4634,4641,4687,5321,5327,6467
NIV 3479,3483,3485,4058,6381,7115
NV 4604,4620,4945

OI 6158,7772,7774,7775,8446,9263
[OI] 5577,6300,6363
OII 3390,3377,3713,3749,3954,3973,4076,4349,4416,4649,6641,6721
[OII] 3726,3729
[OIII]: 4363, 4959,5007
OV 3145,4124,4930,5598,6500
OVI 3811,3834

NaI 5890,5896, 8183,8195

MgI 3829,3832,3838, 4571,4703, 5167,5173,5184, 5528,8807
MgII 2796,2798,2803, 4481,7877,7896,8214,8235,9218,9244,9632

SiII 4128,4131,5958,5979,6347,6371
SII 5433,5454,5606,5640,5647,6715, 13529,14501

CaII 3159,3180,3706,3737, 3934,3969, 8498,8542,8662
[CaII] 7292,7324

FeII 4303,4352,4515,4549,4924,5018,5169,5198,5235,5363
FeIII 4397,4421,4432,5129,5158

---
WR_WN lines: H: 4341,4861,6563; HeII: 4686,5411,10124; CIV: 5801; NIII: 4641; NIV: 4058,4537,7109,7123; NV: 4604,4945
WR_WC/O lines: H: 4341,4861,6563; HeI: 7065,6678,5876,4472,3886; HeII: 4686; CII: 7236; CIII: 4647,5696,6742,9711; CIV: 5801,7726; OV: 5598; OVI: 3811,3834
---
Tellurics: 6867-6884, 7594-7621
Galaxy lines: H 4341,4861,6563; NII 6548,6583; [OII] 3727; [OIII] 4959,5007; NaI 5890,5896; MgII 2798; SII 6717,6731; CaII H&K 3969,3934;
ZnII 2025; CrII 2056,2062,2066; FeII 2249,2260,2343,2374,2382,2586,2599; MnII 2576,2594; MgI 2852
```

**Comment by kmshin1397** [comment]
@rjoebruch Was this issue fully addressed by your PR?

**Comment by simeonreusch** [comment]
I have to back @steveschulze here, having Tellurics and the possibility to add custom lines would be great!

**Comment by rjoebruch** [comment]
Tellurics were coded in at the end of may. Not pushed yet? 
--
Rachel

**Comment by stefanv** [comment]
@rjoebruch We are grateful for your contribution!  Just note that PRs need a bit of handholding from your side to be seen through the review process.  You have comments waiting here: https://github.com/skyportal/skyportal/pull/1993

**Comment by rjoebruch** [comment]
Hi Stefan, thank you for pointing it out. 
I’m sorry, I realise that my mail was a bit dry. I was in a rush and did not think of the form. It was not my intention to come out dry! 

Will look into it, thanks
--
Rachel

**Comment by stefanv** [comment]
@rjoebruch No worries at all!

**Comment by dmitryduev** [comment]
I think that most of the stuff (if not everything) in this issue has been implemented, so closing.
