### ISSUE TITLE
Truncated legend on spectroscopy plot

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#13]
Hi,

The legend of the spectra is truncated.

Cheers,

Steve

![Screenshot from 2020-10-20 12-01-14](https://user-images.githubusercontent.com/11585543/96564577-01566680-12cc-11eb-9fc5-41721b28515e.png)

**Comment by stefanv** [comment]
Let's see how this looks once https://github.com/skyportal/skyportal/pull/1293 goes in.

**Comment by stefanv** [comment]
Names are truncated, but the horizontal scroll bar allows you to view them in full.

**Comment by acrellin** [comment]
Let's leave off telescope name in legend, but viewable in a tooltip

**Comment by steveschulze** [comment]
This would be great. This provides no additional information. The users usually know which instrument is mounted at which telescope.
