### ISSUE TITLE
Feature request: Alphabetizing the telescope list on the dashboard

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#14]
Hi,

Could you alphabetise the telescope list on the dashboard?

The Gemini telescopes are written as GS and Gemini North. It would be more useful to have a consistent naming scheme. :)

How can I watch the status of multiple telescope sites?

Cheers,

Steve

**Comment by acrellin** [comment]
Addressed by https://github.com/skyportal/skyportal/pull/1162
