### ISSUE TITLE
User lists should be alphabetical

### ISSUE THREAD

**Issue by doccosmos** [fritz-marshal/fritz-beta-feedback#15]
When adding users to a new group or selecting additional admins for a group, the current dropdown of users seems randomly ordered. It would be much easier if this was sorted alphabetically.

**Comment by igorandreoni** [comment]
Even better if name + surname (+institution?) could be displayed, instead of usernames. Thanks!

**Comment by acrellin** [comment]
Addressed by https://github.com/skyportal/skyportal/pull/1279
