### ISSUE TITLE
Scanning page comments

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#17]
Hi,

Thanks for the improved scanning page! I agree with Jesper that several of the previous comments still apply. This would be my list.

High priority
-Time axis has to be in units of time from now. MJD is useless if you want to judge whether a transient is 2 or 20 days old.
-Reject options like on the old Marshal
-Menu “Show previously saved candidates?” like on the old Marshal
-If a classification available, show it (don't know whether this feature already exists).
-Examine option of the cut-outs. Critical for fast and young transient experiments.
-ZTF image cutouts have a too-small dynamic range.

Low priority
-Colours of the ZTF filter changes depending on the number of filters. The colour of the filters should be fixed: g = green, r = red, i = yellow
-Annotations should be collapsed by default. This makes it easier to judge which filters a given alert passed.
-Offer an option to export candidate list to a text file
-Reduce white space between postage stamps.

Cheers,

Steve

**Comment by acrellin** [comment]
@steveschulze there is already a checkbox for toggling previously saved candidates.

**Comment by steveschulze** [comment]
Right, but we need the same options as on the old Marshal. We also need options to remove transients from the scanning page.

**Comment by steveschulze** [comment]
There is a bug in the TNOW estimate. There is a case with a future data point.

![Screenshot 2020-10-31 at 07 13 41](https://user-images.githubusercontent.com/11585543/97771746-bef11d00-1b48-11eb-87a7-f6c7182eefbb.png)

**Comment by steveschulze** [comment]
The JD calculation is incorrect. The screenshot is from this morning. It says that TNOW is 2459145.66, but it's ~2459153.5. Also TNOW is given in JD not MJD.

![Screenshot 2020-10-31 at 07 27 28](https://user-images.githubusercontent.com/11585543/97771933-9c600380-1b4a-11eb-9d2f-072e2fac4f2b.png)

**Comment by steveschulze** [comment]
What surprises me further: 
-We specify the format of the auto-annotation value in the filter but this gets ignored
-The values of the auto-annotation can't be marked and copied. This is needed.

**Comment by steveschulze** [comment]
> Also TNOW is given in JD not MJD.

The mislabeling of the JD is a bug in my filter.

...

Digging into this deeper. Our filter gets (M)JD_NOW from $candidate.jd. The displayed light curve on the scanning page goes beyond 2020-10-21 (which corresponds to (M)JD_NOW). Have there been any reingestions?

**Comment by dannygoldstein** [comment]
@steveschulze can you please split this up into individual issues?
