### ISSUE TITLE
Object page

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#18]
Hi,

and comments on the object page.

**High priority**
-Examine option of the cut-outs
-Improve the dynamic range of the ZTF cut-outs
-Observability option
-Absolute magnitude on the right y-axis of the light curve plot. Not shown even when redshift exists.
-Spectra are not displayed (Dima and Danny have pointed me to the thread where the spectral module is discussed.)
-Auto-annotations have to include when and by whom an alert was saved and/or removed from a specific program (date and hour are needed; critical for fast and young transient experiments). Even when manually adding a source. The "Source save history" is not a good solution. We sometimes need to inspect this quickly.

-Besides the object page dashboard, dedicated photometry and spectroscopy pages (to view/access the full data and properties)
-Photometry table without the need to export the light curve
-Option to inspect the full alert packages.
-Option to only show positive subtractions. Vital for all SN experiments (previously discussed on Slack).
-Option to force-check whether all ZTF Photometry is shown in the light curve.
-Option to ingest photometry from PS1 DR2 and (i)PTF

**Medium priority**
-If the window size is changed, the comment section behaves differently from the rest.
-Cut-outs should have at most 3 elements per row. Doesn't work always (see attached picture).

**Low priority**
-Fontsize in the survey sections doesn't seem to be the same for all elements.
-CRTS and FIRST buttons have a different structure. You can't right-click them to open in new tab.
-IRSA/PTF search is not performed.
-IRSA/WISE search fails.

Cheers,

Steve

![Screenshot from 2020-10-28 09-53-31](https://user-images.githubusercontent.com/11585543/97408463-ca540680-1904-11eb-90ec-fa91687b303c.png)

**Comment by steveschulze** [comment]
**Highest priority**
-Automatically query the TNS and add information of the object: IAU name, redshift etc. Can be added to the auto-annotations.

**Medium priority**
-Add a button to report a source to the TNS

**Low priority**
-The colours in the offset plot have to be identical to the designated ZTF-filter colours. E.g., sometimes ZTF/r is shown in blue.
-Surveys: Add the option to search Astronote

**Comment by steveschulze** [comment]
-The cut-outs of the DESI DR8 images don't work. For instance, ZTF18acenqto was covered by the Legacy Surveys.
-The PS1 cut-out should contain a link to the PS1 image cut-out server.

**Comment by dannygoldstein** [comment]
@steveschulze Please split these into separate issues in the future so we can track them. There is too much going on in this issue for us to meaningfully keep track of what it encompasses. Each issue should relate to no more than one request / bug /

**Comment by dannygoldstein** [comment]
> -Examine option of the cut-outs

Please open a separate issue describing what you want here. 

> -Improve the dynamic range of the ZTF cut-outs

https://github.com/dmitryduev/kowalski/pull/22

> -Observability option

https://github.com/skyportal/skyportal/search?q=observability&type=issues

> -Absolute magnitude on the right y-axis of the light curve plot. Not shown even when redshift exists.

This has been implemented for about a month - 

See e.g., https://fritz.science/source/ZTF20abyzomt

-Spectra are not displayed (Dima and Danny have pointed me to the thread where the spectral module is discussed.)

What are you referring to here? The spectra show up fine for me (again, e.g., https://fritz.science/source/ZTF20abyzomt)

-Auto-annotations have to include when and by whom an alert was saved and/or removed from a specific program (date and hour are needed; critical for fast and young transient experiments). Even when manually adding a source. The "Source save history" is not a good solution. We sometimes need to inspect this quickly.

You can mouse over the groups chip on the source page to see when it was saved. 

-Besides the object page dashboard, dedicated photometry and spectroscopy pages (to view/access the full data and properties)

Photometry can be seen as a searchable list on the share data page 

Spectroscopy page is in progress here

https://github.com/skyportal/skyportal/pull/1253

More responses soon.. have to run to a meeting.

**Comment by dannygoldstein** [comment]
> -Photometry table without the need to export the light curve

Why do you need this?

> -Option to inspect the full alert packages.

This already exists,

https://fritz.science/alerts/ztf/ZTF20abyzomt

> -Option to only show positive subtractions. Vital for all SN experiments (previously discussed on Slack).

This is coming in through 

https://github.com/dmitryduev/kowalski/pull/21

> -Option to force-check whether all ZTF Photometry is shown in the light curve.

This should no longer be needed, all ZTF photometry that we know of is always posted to sources immediately cc @dmitryduev 

> -Option to ingest photometry from PS1 DR2 and (i)PTF

https://fritz.science/upload_photometry/ZTF20abyzomt
http://skyportal.io/docs/api#/paths/~1api~1photometry/post

> -If the window size is changed, the comment section behaves differently from the rest.
This is intentional.

> -Cut-outs should have at most 3 elements per row. Doesn't work always (see attached picture).
Wontfix. We want to use all the available space for cutouts, if there is more space then we will use it (that may mean 4 or 5 or even 6 cutouts per row depending on your screen size).

**Comment by stefanv** [comment]
I am going to close this compound issue for now.  Please create issues for each individual issue, wherever still applicable, and we will gladly respond to each.
