### ISSUE TITLE
missing photometry

### ISSUE THREAD

**Issue by yaoyuhan** [fritz-marshal/fritz-beta-feedback#2]
Hi -- I just saved the source https://private.caltech.edu/source/ZTF20aceyolc, but compared with its photometry on the old Marshal (http://skipper.caltech.edu:8080/cgi-bin/growth/plot_lc.cgi?name=ZTF20aceyolc), there are less data points on the Fritz page. May I know what is the reason for this?

Thanks,
Yuhan

![Screen Shot 2020-10-19 at 8 25 43 AM](https://user-images.githubusercontent.com/20339854/96472060-e0ffac80-11e4-11eb-90f1-f4716de96bbb.png)
![Screen Shot 2020-10-19 at 8 25 57 AM](https://user-images.githubusercontent.com/20339854/96472070-e3620680-11e4-11eb-8a21-b0c2c648fcea.png)

**Comment by dmitryduev** [comment]
Fixed in [this Kowalski PR](https://github.com/dmitryduev/kowalski/pull/14)
