### ISSUE TITLE
Sandbox feature for filter/api development.

### ISSUE THREAD

**Issue by wombaugh** [fritz-marshal/fritz-beta-feedback#20]
I would be useful with a sandbox group/filter where api connections can be developed and tested without either having to create new groups all the time or polluting/interfering with existing ones. A sandbox can be emptied regularly (daily) except for some sample interaction objects.

**Comment by dannygoldstein** [comment]
@wombaugh Not quite sure I understand what you want to do here. Can you say a little more about your use case?

**Comment by wombaugh** [comment]
The use case would be to experiment with e.g. new filters and sources, without having to worry about disturbing live science program or having the administrative overhead work of setting up filters/groups for this. The [TNS sandbox](https://sandbox-tns.weizmann.ac.il/search) is a good example of how this can work.

**Comment by stefanv** [comment]
@dmitryduev Does the current sandboxing environment provided via Kowalski allow for this, or do we need to build additional functionality?

**Comment by dmitryduev** [comment]
There's actually a Sandbox group with empty filters that we've created a while ago, but evidently I forgot to actually add folks to it. Just did so (added both Jakobs) -- feel free to flood. [The candidates would get vacuumed in a week, as always.]
Closing this.
