### ISSUE TITLE
Request admittance to a group

### ISSUE THREAD

**Issue by igorandreoni** [fritz-marshal/fritz-beta-feedback#21]
It would be good to have all the group names displayed somewhere and an easy way to join them. For example, it could be there a button to send a request to join directly to the admins of the group. If this is too complicated, we should be able at least to see the name and email of the PI/admin that we have to contact.

**Comment by dmitryduev** [comment]
@acrellin would you mind taking this one on? This was also brought up by Shri recently.

**Comment by acrellin** [comment]
@dmitryduev sure thing. How about a "requested to join" table on the group page that admins can view, with accept/decline buttons for each request?

**Comment by dmitryduev** [comment]
Sounds good! + a "request joining" button for each group that a user is not a member of or something like that.
