### ISSUE TITLE
Contrast settings of cut-outs

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#24]
Hi,

The contrast settings of the ZTF cut-outs need some further tuning in case of very bright sources or for vignetted images (an example is attached).

<img width="919" alt="Screenshot 2020-11-11 at 18 41 21" src="https://user-images.githubusercontent.com/11585543/98845450-041d2500-244e-11eb-8fe9-05f18db3f188.png">

**Comment by dannygoldstein** [comment]
fixed by https://github.com/dmitryduev/kowalski/pull/38
