### ISSUE TITLE
Scanning page: What does "Show previously saved objects mean"?

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#26]
Hi,

What exactly does the option "show previously saved object" mean? After choosing this option, some saved objects are still shown. We need the same functionality as on the old Marshal to specify what we want to see and what not.

Screenshots are attached.

<img width="1244" alt="Screenshot 2020-11-12 at 08 24 16" src="https://user-images.githubusercontent.com/11585543/98908364-98c06b00-24c0-11eb-9068-49566d2231d9.png">

<img width="723" alt="Screenshot 2020-11-12 at 08 27 45" src="https://user-images.githubusercontent.com/11585543/98908673-0ec4d200-24c1-11eb-89be-38e8ec340dd3.png">

**Comment by dannygoldstein** [comment]
Hi @steveschulze, 

> What exactly does the option "show previously saved object" mean?

Do you mean in the context of the growth marshal? Or "the show only unsaved candidates" option in fritz?

**Comment by steveschulze** [comment]
Hi Danny,

The Fritz option.

It would be very useful if would have similar functionality as on the GROWTH Marshal to display saved objects or not.

**Comment by dannygoldstein** [comment]
@kmshin1397 and @acrellin  can comment on this

**Comment by kmshin1397** [comment]
Hi @steveschulze,

Sorry for the delayed response - apparently I didn't have notifications enabled for this repository.

The "Show only unsaved candidates" option will filter for candidates that have yet to be saved to the groups you have selected in that "Program selection" form right below it. Thus, you could still see candidates show up as previously saved if they have been saved to other programs and just haven't been saved to the programs you currently have selected on the scanning page. I hope that answers your question.

Please feel free to file a new feature request issue for adding a "Show only saved candidates" option if you feel that it would be very useful to have. Note that you can already go to the group sources page (which you can navigate to from the "Groups" page on the sidebar) to look at all the objects saved to a particular group (although the tables on the group sources page does not yet have the sophisticated filter/sort logic that is on the scanning page yet, so I can see why you would want this).

**Comment by stefanv** [comment]
The question has been answered, so I am closing for now.  Refer to #27 for feature request.
