### ISSUE TITLE
Object rejection on the scanning page

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#27]
Hi,

It is critical to have the option to remove objects from the scanning page because they are bogus, not relevant for a specific program, stars etc. A screenshot with the rejection options from the old Marshal is attached.

<img width="249" alt="Screenshot 2020-11-12 at 08 27 52" src="https://user-images.githubusercontent.com/11585543/98908942-6feca580-24c1-11eb-869c-a902479ec6bf.png">

**Comment by dmitryduev** [comment]
I would reformulate this as follows: 
- add an option to add classifications directly from the scanning page
- add a filtering option for previously classified objects

**Comment by stefanv** [comment]
@dmitryduev @acrellin Can we agree on what a satisfactory solution to this would be?

**Comment by stefanv** [comment]
Related to https://github.com/fritz-marshal/fritz-beta-feedback/issues/26

**Comment by dmitryduev** [comment]
@Yashvi-Sharma sent an invite to you - will tag here once you've accepted. Thanks!

**Comment by guynir42** [comment]
closed by skyportal/skyportal#1757
