### ISSUE TITLE
Not all photometry is shown on the object page

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#28]
Hi,

The number of photometry of ZTF20abzumlr is different on https://fritz.science/alerts/ztf/ZTF20abzumlr and https://fritz.science/source/ZTF20abzumlr.

<img width="570" alt="Screenshot 2020-11-12 at 09 16 53" src="https://user-images.githubusercontent.com/11585543/98913671-f7d5ae00-24c7-11eb-93f9-2f3444a35fe6.png">

<img width="680" alt="Screenshot 2020-11-12 at 09 16 48" src="https://user-images.githubusercontent.com/11585543/98913665-f60bea80-24c7-11eb-9216-cbb826c33818.png">

**Comment by dmitryduev** [comment]
Unfortunately, this is a feature, not a bug: this object was saved to the RCF program, which only has access to programid=1 data, so only that data were propagated.

**Comment by dannygoldstein** [comment]
Ah!
