### ISSUE TITLE
Telescope coordinates are incorrect on Fritz

### ISSUE THREAD

**Issue by dannygoldstein** [fritz-marshal/fritz-beta-feedback#29]
Some of the telescopes have longitudes in the domain [0, 360], while others have longitudes in the (correct) domain [-180, 180]. This breaks the observability page: 

![Screen Shot 2020-11-12 at 3.24.07 PM.png](https://images.zenhubusercontent.com/59e2c99cb0222d5de47baddd/70162af6-59f8-4d37-8cee-ab4c6141c9fa)

Need to correct these longitudes so they are on the right system.

**Comment by profjsb** [comment]
Suppose you could handle out of bounds data with a mod operator, rather than fix the data (ie. make the backend more robust).

**Comment by profjsb** [comment]
Also, dont show an airmass plot for satellites.
