### ISSUE TITLE
Scrambled text after creating a new group

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#3]
Hi,

after creating a group, some text gets scrambled (see attached picture)

Cheers,

Steve
![Screenshot from 2020-10-19 13-44-37](https://user-images.githubusercontent.com/11585543/96552820-fcd68180-12bc-11eb-91ca-c0899b83dda8.png)

**Comment by acrellin** [comment]
Fixed in https://github.com/skyportal/skyportal/pull/1161
