### ISSUE TITLE
[Feature Request] - Add Save to Favorites Button to Save Interesting Sources 

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#31]
Can each user have a list of "Favorite Sources" somewhere on the dashboard? Similar to the GM, each source had the option to be saved to a list of favorite candidates. Would it be possible to add something like this to Fritz?

**Comment by dannygoldstein** [comment]
Duplicate of https://github.com/skyportal/skyportal/issues/1310
