### ISSUE TITLE
[Feature Request] - Spectra Summary Page 

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#33]
On the GM we had this feature on the home paged called **Spectra Summary**. Essentially, the user was able to query for a given date all the spectra that have been uploaded in that date range to GM and filter it by **classification**, **instrument**, and **science program**. It would be awesome if we can add this feature somewhere in Fritz, and it would help a lot in managing our classification and spectra.

**Comment by dannygoldstein** [comment]
Will be addressed by skyportal/skyportal#1253
