### ISSUE TITLE
[Feature Request/Question] - Expanding Instrument List 

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#34]
Suppose we wanted to upload a spectrum from a telescope that is currently not on the current instrument list (in the upload spectrum section of each source). Are there any existing methods (API and manually) to add new telescopes to the instrument list?

**Comment by dannygoldstein** [comment]
Yes:

http://skyportal.io/docs/api#/paths/~1api~1telescope/post
http://skyportal.io/docs/api#/paths/~1api~1instrument/post

However, only users with a "Manage telescopes" and "Manage instruments" ACL can use these endpoints. We do this so that duplicate instruments and telescopes are not posted.

**Comment by dannygoldstein** [comment]
(You can check your ACLs on your Profile page).
