### ISSUE TITLE
[Feature Request] - Expanding the Classification Taxonomy 

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#35]
Is there currently any discussion about the possibility of expanding the current classification taxonomy list, if can we add a method for the user to create a new classification type? For example, there are many kinds of (sub-types of Type Ia supernovae) and other kinds that are currently not on the classification/taxonomy list.

**Comment by dannygoldstein** [comment]
You can create your own taxonomies using this endpoint:

http://skyportal.io/docs/api#/paths/~1api~1taxonomy/post

Take a look at this package for more on how to structure a taxonomy:

https://github.com/profjsb/timedomain-taxonomy
