### ISSUE TITLE
[Feature Request] - Add Important ZTF-Related Links 

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#36]
Somewhere on the dashboard, ideally, right next to the observatory forecast/webcam, it would be nice to add a tab for the following: 

1. P48 live status
2. P60 live status
3. ZTF schedule survey plan

**Comment by dannygoldstein** [comment]
@andytza Where is this information served? Can you provide a link for each of these?

**Comment by dannygoldstein** [comment]
E.g., if I want to know the P48 status, I would go to link X

**Comment by AndyTza** [comment]
@dannygoldstein  Yep, here are the related links: 
1. P48 status: http://skyvision.caltech.edu/ztf/
2. P60 status: http://pharos.caltech.edu/login
3. ZTF schedule survey plan: https://sites.astro.caltech.edu/~tb/iptfdir/prv/p48ops/

**Comment by dannygoldstein** [comment]
For 1 and 2 what are the credentials? And would it be a problem to store them in an open source repository? 

For 3, it says it was last updated in 2017 (for iPTF). Presumably there is one for ZTF?

**Comment by AndyTza** [comment]
Let me ask around first, and I will get back to you @dannygoldstein!

**Comment by dannygoldstein** [comment]
It would be most helpful if, for 1 and 2, the developers could add public endpoints (no authentication required), that returned the status as JSON when I submit a GET. 

E.g., 

```
requests.request('GET', 'http://skyvision.caltech.edu/ztf/status')
```
returns
```
{'status': 'online'}
```
or 
```
{'status': 'down'}
```
with no auth required. Similar for p60.

**Comment by dannygoldstein** [comment]
Moving to unscheduled until we can determine how to access the data needed

**Comment by rswalters** [comment]
As administrator of the first two links I can work on creating an api call to get the status of the telescope.

**Comment by AndyTza** [comment]
I was told that the up-to-date ZTF schedule survey plan link is currently a work in progress... I will notify you all when this is done!

**Comment by ebellm** [comment]
Regarding the ZTF schedule: the private schedule is private, so some simple authentication is going to be necessary to get that data.

The scheduler exposes the planned schedule now, but the security model on the mountain means it's painful to access.  I have an overdue task to provide a pointing plan reporting service for the _public_ surveys; my plan is to wrap up an authenticated version that includes the private pointing plan as well.

**Comment by stefanv** [comment]
I am going to close this issue for now, since we cannot act on it. Feel free to re-open or create a new issue when the above interfaces are available.
