### ISSUE TITLE
permissions to delete and edit sedm requests

### ISSUE THREAD

**Issue by jespersollerman** [fritz-marshal/fritz-beta-feedback#38]
I want to have permission to remove sedm trigger for https://fritz.science/source/ZTF20acpjapi
New
danny  7:13 AM
Currently we dont let people delete other peoples’ requests
jesper  7:22 AM
How do we change this?
stefanv  7:24 AM
You can file a feature request at https://github.com/fritz-marshal/fritz-beta-feedback
fritz-marshal/fritz-beta-feedback
A place for beta testers to discuss issues or request new features related to the Fritz Marshal
Last updated
a month ago
<https://github.com/fritz-marshal/fritz-beta-feedback|fritz-marshal/fritz-beta-feedback>fritz-marshal/fritz-beta-feedback | Oct 13th | Added by GitHub

**Comment by dannygoldstein** [comment]
Needs approval from @mansikasliwal, @doccosmos, and @rswalters

**Comment by rswalters** [comment]
I approve this functionality for the SEDM Czar which Jesper is currently designated.

**Comment by dannygoldstein** [comment]
ok, I have provisionally granted @jespersollerman the ability to delete any RCF SEDM request. Will talk tomorrow with @mansikasliwal and @doccosmos  to potentially expand this privilege

**Comment by acrellin** [comment]
Mansi prefers only allowing the owner to delete
