### ISSUE TITLE
Seeing double when hovering over a data point

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#4]
Hi,

When hovering over a data, you see the record twice.

![Screenshot from 2020-10-19 13-07-27](https://user-images.githubusercontent.com/11585543/96552986-2c858980-12bd-11eb-8864-827103a4810b.png)

**Comment by dannygoldstein** [comment]
Fixed in skyportal/skyportal#1071 and skyportal/skyportal#1111
