### ISSUE TITLE
Palomar starlist format not correct

### ISSUE THREAD

**Issue by virajkaram** [fritz-marshal/fritz-beta-feedback#45]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
The targetlist for P200 generated by Fritz is not accepted by the P200 system. There are several formatting issues.

**To Reproduce**
1. Go to 'Observing runs '
2. Click on any observing run ex. 
3. Scroll down to 'Starlists and offsets'
4. Click Facility -> select P200
5. The targetlist is not in the P200 format

**Expected behavior**
The expected format of the P200 targetlist is as follows - 
20 characters for target name (if name<20 chars, remaining chars are blank)
2 characters for RA hours, 1 space 2 characters for RA minutes, 1 space, 2 characters for RA seconds
2 spaces 
2 characters for Dec deg, 1 space, 2 characters for Dec minutes, 1 space, 2 characters for Dec seconds
1 space
2000.0, 2 spaces, !, comments
Example :
ZTF20acppuiq        00 09 01.32  -08 35 54.76 2000.0  ! source_name=ZTF20acppuiq

**Platform information:**
 - Fritz version: v0.9.dev0+git20201117.9e4dd70
 - Browser
   -  I'm browsing on a desktop

**Additional context**
It will also be helpful if the following standard stars are added to the list
G191-B2B            05 05 30.60  +52 49 56.0  2000.0  ! Standard
Feige34               10 39 36.71  +43 06 10.1  2000.0  ! Standard
Feige67               12 41 51.83  +17 31 20.5  2000.0  ! Standard
Feige110             23 19 58.39  -05 09 55.8  2000.0  ! Standard
BD+28d4211        21 51 11.07  +28 51 51.8  2000.0  ! Standard
BD332642           15 51 59.89  +32 56 54.3  2000.0  ! Standard

**Comment by profjsb** [comment]
It's generated correctly on the backend but not rendering correctly. Will look for a fix.
