### ISSUE TITLE
Permission issue with observing runs

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#46]
Please fill out relevant sections below; remove those that are unused.

I want to flag an object as observed. However, Fritz complains that I do not have permission to do so. 

**Expected behaviour**
Everybody should be able to change the status of an observation. We need to focus on science, not bureaucracy!

**Comment by dannygoldstein** [comment]
Hi @steveschulze, please fill out the bug report fully. Currently there is not enough information for us to isolate and reproduce the issue.

**Comment by dannygoldstein** [comment]
Closing in favor of #46 which provides sufficient information to reproduce the issue.
