### ISSUE TITLE
No support for UVOT filters

### ISSUE THREAD

**Issue by erezimm** [fritz-marshal/fritz-beta-feedback#47]
When uploading swift photometry from UVOT the filters are not recognized and are not supported in the documentation here: https://skyportal.io/docs/api.html#/paths/~1api~1photometry/put, specifically there is no filter field for UVW2, UVM2 and UVW1 UVOT filters.
I understand this was supported before on fritz so i submit this as a bug.

**Comment by dannygoldstein** [comment]
Fixed by https://github.com/skyportal/skyportal/issues/1308

**Comment by steveschulze** [comment]
Hi, I tried to upload UVOT data today but it failed. Do you know when we can upload UVOT data again? This is a critical issue. We observe very often transients with Swift. These observations are critical to deciding on the follow-up with various other telescopes.

**Comment by dannygoldstein** [comment]
Should work now

**Comment by dannygoldstein** [comment]
Just had to update the filters on the instrument in the database
