### ISSUE TITLE
Update coordinates to be in format that is more easily parsed to other tools and include them in degrees.

### ISSUE THREAD

**Issue by katemaguire** [fritz-marshal/fritz-beta-feedback#49]
Current objects coordinates on Fritz are "02h54m59.2s  +04d03m36.87s", which don't parse well to other tools. Request to be updated to the format "17:25:39.16 +59:26:48.4" as on Growth Marshall. Also would be good to have in degrees too as on GM.

**Comment by dannygoldstein** [comment]
Degrees are already included, look to the right  of the hexadecimal coords. I am fine to update the hexadecimal coords to colon notation.

**Comment by dmitryduev** [comment]
Implemented, closing.
