### ISSUE TITLE
Features needed for the photometry and spectroscopy tools

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#5]
Hi,

The photometry and spectroscopy should have dedicated pages and not only show up on the object dashboard. We need to see the photometry as a table without downloading the light curve.

Which features are supposed to go into the spectroscopy tool? Do you plan display lines like on the old Marshal? If yes, which lines are you going to add to the catalogue?

Cheers,

Steve

**Comment by dannygoldstein** [comment]
> The photometry and spectroscopy should have dedicated pages and not only show up on the object dashboard. We need to see the photometry as a table without downloading the light curve.

Spectroscopy has a dedicated page in development, 

https://github.com/skyportal/skyportal/pull/1253

Why do you need the photometry table as a page ? 

> Which features are supposed to go into the spectroscopy tool? Do you plan display lines like on the old Marshal? If yes, which lines are you going to add to the catalogue?

![Screen Shot 2020-11-02 at 2.18.58 PM.png](https://images.zenhubusercontent.com/59e2c99cb0222d5de47baddd/79e25a9c-9884-453b-84a1-8031c37733ad)
