### ISSUE TITLE
Different offset stars in the finder and starlist

### ISSUE THREAD

**Issue by virajkaram** [fritz-marshal/fritz-beta-feedback#50]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
For some sources, the offset stars in the starlist and those in the finder chart are different

**To Reproduce**
1. Go to 'Observing Runs'
2. Click on '2020-11-18 DBSP/Palomar 5.1m Hale (PI: Shri Kulkarni / Group: Redshift Completeness Factor)'
3. Scroll down to 'ZTF20abfcszi'
4. Click on PDF finder chart. Note coordinates of ZTF20abfcszi_o2 and ZTF20abfcszi_o3
5. Scroll further down to Starlist. Select Facility as P200. The coordinates of ZTF20abfcszi_o2 and ZTF20abfcszi_o3 in the starlist are different from the ones noted in step 4.
6. Same error for multiple other sources including ZTF20acqxzdy_o2 and ZTF20acqxzdy_o3, ZTF20achaxsk.

**Expected behavior**
The offset stars and offsets in the finder and the starlist should be exactly the same!

**Screenshots**

**Platform information:**
 - Fritz version:  v0.9.dev0+git20201117.9e4dd70
 - Browser
   - [ ] I'm browsing on a desktop

**Additional context**

**Comment by guynir42** [comment]
@josh I recall you've made some upgrades to the finder... is this issue still relevant?

**Comment by mcoughlin** [comment]
@virajkaram It is identical now so will close. Please reopen if further issues.
