### ISSUE TITLE
[Bug Report + Feature Request] Data in Bokeh Lightcurve Plots Not Showing Labels

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#53]
**Describe the bug**
For many CLU sources (i.e ZTF19abekmfr is just one example) the bokeh lightcurves data points are missing their labels (i.e mjd, flux...). 

**To Reproduce**
1. Go to source ZTF19abekmfr
2. Scroll down to lightcurve, and try to click on one data point from the photometry to see the labels of each point.
3. See missing entries

**Expected behavior**
Typically we expect that these labels are filled with the associated data. 

**Additional Feature Request** 
In this list of labels, can we please also add the **program_id** of each detection?

**Screenshots**
<img width="669" alt="Screen Shot 2020-11-23 at 1 38 44 PM" src="https://user-images.githubusercontent.com/22720676/100001875-c3000b80-2d91-11eb-8cbf-58e62db94995.png">

**Platform information:**
 - Fritz version:  v0.9.dev0+git20201118.8603e11
 - Browser
   - I'm browsing on a desktop (Google Chrome)

**Comment by dannygoldstein** [comment]
@andytza - I can't reproduce this. The points all show up for me.

**Comment by stefanv** [comment]
@AndyTza Could you point us to a specific source that exhibits this behavior?

**Comment by AndyTza** [comment]
Hi @stefanv, 

It seems like the labels are not working for me for any given source (i.e **ZTF19abekmfr**, was is just one example). I am not sure if this is linked to my account specifically. Thanks so much!

**Comment by stefanv** [comment]
Thanks, @AndyTza. This is still the case now?

**Comment by AndyTza** [comment]
@stefanv Yep, still nothing. 

<img width="1423" alt="Screen Shot 2020-12-02 at 9 32 39 PM" src="https://user-images.githubusercontent.com/22720676/100956219-01aa6a00-34e6-11eb-94f1-2249960c239a.png">

**Comment by stefanv** [comment]
I'm afraid I can't replicate.  Could you try ctrl-shift-R to see if a JavaScript refresh helps?

**Comment by AndyTza** [comment]
@stefanv it started working this morning. Thank you so much! 👍

**Comment by stefanv** [comment]
![image](https://user-images.githubusercontent.com/45071/101130622-aa28fe80-35b8-11eb-8a25-6fb50a2133bf.png)

**Comment by stefanv** [comment]
![simon_the_sorcerer-simon2a](https://user-images.githubusercontent.com/45071/101130707-cfb60800-35b8-11eb-895f-870bf41a4128.gif)
