### ISSUE TITLE
Highlight CLU_z for CLU sources and add absolute magnitude automatically

### ISSUE THREAD

**Issue by dekishalay** [fritz-marshal/fritz-beta-feedback#55]
Thanks for making the CLU program so fast and easy to access!!

**Feature Summary**
One of the primary parameters we check for saved sources in CLU is the redshift of the host galaxy. For CLU crossmatched sources, this information is in the "z" parameter in the auto-annotations. Currently, the information is present inside a long list of other auto-annotations (inside 'cross_matches_CLU') for each saved source. To make the source examination accessible, would it be possible to bring the list of "z" and and "distance_arcsec" outside that long list (inside cross_matches_CLU) and put it as auto-annotation fields in themselves for the source? In practice, it would also benefit if the "z" for the nearest CLU crossmatch could be automatically set as the tentative redshift when a source is saved to determine the absolute magnitude of the light curve.

**Usage / behavior**
We would like the redshift "z" and distance "distance_arcsec" for each cross-matched CLU galaxy to be shown as separate auto-annotations for every source saved in the CLU program. It would be also great to set the redshift of the nearest CLU crossmatch as a tentative default redshift so that we can check the absolute magnitude of the source from the light curve.

**Implementation details**
I think the auto-annotations inside 'cross_matches_CLU' need to be pulled out from the list and set as separate parameters when a source is saved. Similarly the redshift of the nearest CLU galaxy (smallest distance_arcsec) could be set as a tentative redshift when saving.

**Comment by dmitryduev** [comment]
The first part of the request is not really a Fritz issue -- you should implement it in the last stage of your filter:
```
      "annotations.CLU_distance_arcsec": {
        "$map": {
          "input": "$cross_matches_CLU",
          "as": "match",
          "in": "$$match.coordinates.distance_arcsec"
        }
      },
      "annotations.CLU_z": {
        "$map": {
          "input": "$cross_matches_CLU",
          "as": "match",
          "in": "$$match.z"
        }
      },
```
Out of courtesy, I have just added this to the CLU filter and saved the new version.

As for setting the redshift when saving a CLU candidate -- this is too custom to one specific program + the logic even in that case is somewhat ambiguous (e.g. which one to pick if there are three matches?), so I'd say that's a WONTFIX for now. In the (not so near) future when/if we revive the hooks in SP, this might become possible as a custom action upon saving a candidate.
