### ISSUE TITLE
Uploading and viewing permissions for spectra of sources without permission

### ISSUE THREAD

**Issue by dekishalay** [fritz-marshal/fritz-beta-feedback#56]
Kudos to the dev team for creating such an awesome API! It really feels great to have a fast responding API for uploading spectra from reductions :) Thanks for your help in sorting out this bug.

**Describe the bug**
We recently realized that a user that does not have permissions to view a source can upload a spectrum via the API, and then not have access to even viewing the spectrum that they uploaded. I recently uploaded a spectrum for the source ZTF20abgbdpr which was requested by a team member, but I don't have permissions to see the source on fritz (yet). The upload did go through smoothly but I cannot see the spectrum myself because I don't have permissions for the source. 

**To Reproduce**
1. Upload a spectrum to fritz via the API for a source where you do not have permissions
2. Go to the source page
3. I think you still won't be able to see the spectrum uploaded because of permissions.

**Expected behavior**
From talking to the team, it appears that the uploader should have permissions to view the spectrum that they uploaded. So in cases like this, I think the uploader should be able to just see the spectrum that they uploaded for the source at least, even if they don't see anything else.

**Platform information:**
 - Fritz version:  v0.9.dev0+git20201118.8603e11
 - Browser
   - I'm browsing on a desktop (Chrome)

**Comment by scizen9** [comment]
Has this been addressed by the new permissions infrastructure?

**Comment by dmitryduev** [comment]
This has been addressed by the new permissions infrastructure, closing.
