### ISSUE TITLE
Consistent colors for r band and g band in the scanning page

### ISSUE THREAD

**Issue by erezimm** [fritz-marshal/fritz-beta-feedback#57]
I noticed that in the scanning page if i band exists for a lightcurve then the r band  marker in the lightcurve turns red while i band is orange unlike the case where there have been no i band observations.
It would be nice if r band would always have a red marker, i band a yellow marker and g band a green marker like in the GROWTH marshal.
Thanks!
![image](https://user-images.githubusercontent.com/53300818/100234872-5cffb980-2f34-11eb-9336-331a60da0ac1.png)

**Comment by dmitryduev** [comment]
@stefanv https://github.com/vega/vega-lite/issues/6708 is still an open issue...

**Comment by stefanv** [comment]
Duplicate of https://github.com/skyportal/skyportal/issues/681

**Comment by guynir42** [comment]
Closed as it is a duplicate of SP #681
