### ISSUE TITLE
Too many clicks to save an object on the object page

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#6]
Hi,

The current default option is to save an object to all filters it passes. This is a rare use case. Scanners will save transients to specific programs and not all filters.

At the moment it takes 3 clicks to save a transient to a specific program. This can be reduced to two. If only one program is selected, this program should be the default to which an alert is saved. In case multiple filters are selected, the default program should be the one at the top of the alphabetic ranking.

Having a faster save option is particularly important for SLSN and RCF filters that save many targets every night.

Cheers,

Steve

**Comment by acrellin** [comment]
Addressed in https://github.com/skyportal/skyportal/pull/1168
