### ISSUE TITLE
Improve observability tab

### ISSUE THREAD

**Issue by idoirani** [fritz-marshal/fritz-beta-feedback#61]
Currently, it is hard for the user to find his/hers observatory of interest. I suggest showing the plots only for selected observatories. 

Also, the "hours over airmass 2.5" plot in the growth marshal was very useful in planning observations. Please add it in Fritz as well.

Thanks!
Ido

**Comment by stefanv** [comment]
:wave: @idoirani Thank you for your feedback.

Could you please expand your description of the issue according to our [issue template](https://raw.githubusercontent.com/fritz-marshal/fritz-beta-feedback/master/.github/ISSUE_TEMPLATE/feature_request.md)?

We would like to track issues one by one, so please file an additional issue for the "hours over airmass 2.5" request [by clicking here](https://github.com/fritz-marshal/fritz-beta-feedback/issues/new/choose).

**Comment by kmshin1397** [comment]
Perhaps just selecting which instruments to show via user prefs
