### ISSUE TITLE
SEDm trigger on Fritz from RCF but transient not saved to RCF ? 

### ISSUE THREAD

**Issue by rjoebruch** [fritz-marshal/fritz-beta-feedback#63]
**Describe the bug**
While scanning for RCF, a transient passed the filter and was not previously saved to RCF bbut SEDm was already trigggered on the RCF program 

**To Reproduce**
1. Go to  scanning page, select time 2020-11-26 00:00 until 2020-11-26 23:59
2. Select RCF program and display only unsaved candidates 
3. Scroll down to page 3 

**Expected behavior**
The transient should be saved to the program in order to trigger SEDm?

**Screenshots**
Screen Shot 2020-11-26 at 16 41 44 : on the scanning page
Screen Shot 2020-11-26 at 16 41 54 : the object page (not saved to RCF but only to sitewide group)
Screen Shot 2020-11-26 at 16 42 01 : trigger from RCF program to SEDm

**Platform information:**
 - Fritz version: : v0.9.dev0+git20201125.95d9e76+fritz.7d7a638.
 - Browser
   - [Chrome ] I'm browsing on a desktop

![Screen Shot 2020-11-26 at 16 41 44](https://user-images.githubusercontent.com/45436034/100364574-fbf4e600-3006-11eb-818b-a6c8e4eeddd2.png)
![Screen Shot 2020-11-26 at 16 41 54](https://user-images.githubusercontent.com/45436034/100364581-ff886d00-3006-11eb-8bd7-7dce75ca3b9b.png)
![Screen Shot 2020-11-26 at 16 42 01](https://user-images.githubusercontent.com/45436034/100364585-00210380-3007-11eb-99c5-2858aae416e8.png)

**Comment by dannygoldstein** [comment]
Currently we allow anyone who is a member of a group to trigger the group's robotic allocations on an Object (regardless of whether the object was saved to the group associated with the allocation).
