### ISSUE TITLE
Online accessible photometry

### ISSUE THREAD

**Issue by rjoebruch** [fritz-marshal/fritz-beta-feedback#66]
We would like to have the following features regarding photometry: 
- (most urgent) an online visualisation of the photometry table (without having to download a CSV file)
- photometric table is arranged according to time (if we could have JD, that would be even better to avoid discrepancy with the marshal) 
- have a measure of the apparent magnitude for detections 
- have a column for program ID (MSIP/partnership/caltech) 

ty!

**Comment by dannygoldstein** [comment]
@dmitryduev Need to close https://github.com/fritz-marshal/fritz/issues/87 to address the last point

**Comment by stefanv** [comment]
@dannygoldstein Want to split that up into a separate issue?

**Comment by dmitryduev** [comment]
All implemented, closing.
