### ISSUE TITLE
Source page displays twice the photometry

### ISSUE THREAD

**Issue by rjoebruch** [fritz-marshal/fritz-beta-feedback#67]
**Describe the bug**
On the source page, the photometry (and spectroscopy) is displayed twice. 

**To Reproduce**
1. Go to source page (e.g. https://fritz.science/source/ZTF20acuaqlf)
2. Scroll down to photometry
4. See error (+see screenshot)

**Expected behavior**
Only one window displaying the photometry 
(and *if possible* making the data points and labels and ticks bigger in size)

(thank you!!) 

**Platform information:**
 - Fritz version:  v0.9.dev0+git20201125.95d9e76+fritz.7d7a638.
 - Browser
   - [Chrome ] I'm browsing on a desktop

![Screen Shot 2020-11-30 at 10 43 53](https://user-images.githubusercontent.com/45436034/100587286-0827be80-32f9-11eb-8b80-5d8c32e8e184.png)

**Comment by dannygoldstein** [comment]
Should be fixed by https://github.com/skyportal/skyportal/issues/1250

**Comment by stefanv** [comment]
Fixed by https://github.com/skyportal/skyportal/pull/1293

**Comment by acrellin** [comment]
The fix for this has been implemented and deployed
