### ISSUE TITLE
Permissions on spectra uploaded through web form not set correctly.

### ISSUE THREAD

**Issue by rlunnan** [fritz-marshal/fritz-beta-feedback#68]
**Describe the bug**
After uploading a spectrum through the web form, even though the "Share With" menu has one or multiple groups selected, in the end only the uploader has permission to see the spectrum.

**To Reproduce**
1. Go to the web form for uploading spectra (e.g. https://fritz.science/upload_spectrum/ZTF20aceicyy) and attempt to upload spectrum through web form.
2. Click on "Share with" menu and select appropriate groups, then fill in the rest of the required information and upload spectrum.
3. After finishing uploading spectrum, it is still only visible to the person who uploaded it. This is verified by clicking the "Share Data" button and viewing current permissions. E.g., the object above has an DBSP spectrum that was uploaded by Lin Yan and attempted shared with the Superluminous Supernova group, but is only visible to her after uploading. 

**Expected behavior**
I expect an uploaded spectrum to be visible to the groups selected in the "Share with..." menu in the web form.

**Comment by dannygoldstein** [comment]
thanks for catching this @rlunnan, I found the cause of the problem and will be pushing up a fix shortly.

**Comment by rlunnan** [comment]
I just attempted to re-upload a spectrum of https://fritz.science/share_data/ZTF20acjaayt, and it is still visible to only me. Either the fix is not yet in effect, or the bug is still there in some form?

**Comment by dannygoldstein** [comment]
Hasn’t been deployed yet

________________________________
