### ISSUE TITLE
Galactic extinction doesn't work

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#7]
Hi,

I tried to get the Galactic extinction of ZTF18acenqto. When I press the button. I get the following output.
![Screenshot from 2020-10-20 11-14-00](https://user-images.githubusercontent.com/11585543/96559238-6f4b5f80-12c5-11eb-8614-b291c6a816ee.png)

Cheers,

Steve

**Comment by dannygoldstein** [comment]
Fixed in skyportal/skyportal#992
