### ISSUE TITLE
Comments bubbles

### ISSUE THREAD

**Issue by sgezari** [fritz-marshal/fritz-beta-feedback#70]
The bubbles around the comments on each source page take up too much room.  You have to scroll to see all of them.  In the old GROWTH Marshal you could see all the comments easily in one page.  The comments should be all visible at once without having to scroll.  Perhaps changing the format to not have bubbles around the text that take so much room.

**Comment by dmitryduev** [comment]
Will be addressed by https://github.com/skyportal/skyportal/issues/976, closing.
