### ISSUE TITLE
Once an object's redshift is set, add "Rest Wavelength" axis on spectroscopy plot

### ISSUE THREAD

**Issue by rlunnan** [fritz-marshal/fritz-beta-feedback#73]
**Feature Summary**
Once an object has an associated redshift saved, show the corresponding rest wavelength on an x-axis (for example, along the top x axis of the spectroscopy plot). 

**Usage / behavior**
Seeing the rest wavelengths corresponding to the redshift set is extremely helpful contextual information for being able to identify and analyze the features in the spectrum more intuitively. This would be similar to how the "Absolute magnitude" axis appears on the photometry plot once the redshift is set.

**Alternative Solutions**
One could also connect it to the redshift slider feature (so one could inspect directly while experimenting), though the easiest would be that the axis only appears once a redshift is saved, and corresponds to that redshift.

**Implementation details**
Rest wavelength is simply given by observed wavelength / (1+z) where z is the redshift, so this should be straightforward to implement.

**Comment by dannygoldstein** [comment]
@scizen9 can you take this one?

**Comment by scizen9** [comment]
Yes, sign me up!

**Comment by scizen9** [comment]
Implemented with [PR #1591](https://github.com/skyportal/skyportal/pull/1591)
