### ISSUE TITLE
Free text for the observers/reducers in the spectra uploads 

### ISSUE THREAD

**Issue by rjoebruch** [fritz-marshal/fritz-beta-feedback#74]
**Feature Summary**
May we type free text instead of a roll-down menu for the observers and reducers in the spectra upload?

**Comment by dannygoldstein** [comment]
This is how we had it originally; @mansikasliwal specifically requested that we not do this so that spectra always were associated with a user account (so they could be contacted and cited appropriately in papers).

**Comment by rjoebruch** [comment]
I see... this should indeed facilitate the citation. 
But what do we do when uploading spectra from external sources  (eg ZTF20acvjagm, spectra from the EFOSC). I left the observers and reducers fields empty and just added a comment to the object. 
Maybe we could have in the rolldown menu an option called “external” which allows free text? 

Thanks! 

נשלח מה-iPhone שלי

**Comment by stefanv** [comment]
@dannygoldstein Maybe worth discussing this use case with Mansi---there's clear utility.

**Comment by dannygoldstein** [comment]
@rjoebruch In that case, one could leave the fields blank? (they are not required). Is there a pressing need to identify who took /reduced the spectrum when it is coming from an external source (presumably by that point it is already public)?

**Comment by dannygoldstein** [comment]
Mansi says - Hi Danny, Rachel has a point. Please allow external but require a point of contact who is a Fritz user so that someone can be contacted when publishing the data.
