### ISSUE TITLE
Search for alerts by coords

### ISSUE THREAD

**Issue by janvanroestel** [fritz-marshal/fritz-beta-feedback#75]
**Feature Summary**
Search for alerts by coordinates. 

**Usage / behavior**
Similar to the current Fritz "Alerts" tab which allows to search for alerts by ZTF objectID, add a search option for alerts by ra,dec. 

**Implementation details**
This ability was available in the Kowalski Alertlab.

**Comment by noralinn** [comment]
I also missed this feature today! While scanning we wondered whether the second source close to https://fritz.science/source/ZTF21aabpszb is real. The Growth Marshal cone search finally revealed that it was an old SN Ia.

The Growth Marshal would also let you know when a transient is close to a previously saved source. Such a feature would also be useful.
