### ISSUE TITLE
Spectrum is not displayed on the Fritz page

### ISSUE THREAD

**Issue by yaoyuhan** [fritz-marshal/fritz-beta-feedback#76]
**Describe the bug**
I uploaded the spectra for a few objects. Sometimes the spectra do not appear in the plotting figure (such as https://fritz.science/source/ZTF20acqoiyt and https://fritz.science/source/ZTF20acnznms). I can click on “Keck/LRIS (2020-12-12)” option but nothing shows up. And sometimes the upload fails and I get an error of “Out of range float values are not JSON compliant”, such as in https://fritz.science/source/ZTF20abnorit.

**To Reproduce**
The attached file.zip contains the spectra that I uploaded.
[files.zip](https://github.com/fritz-marshal/fritz-beta-feedback/files/5685532/files.zip)

**Screenshots**
![ZTF20abnorit_example](https://user-images.githubusercontent.com/20339854/102025088-7e411200-3d4a-11eb-8cd5-4ffba7656087.png)
![ZTF20acqoiyt_example](https://user-images.githubusercontent.com/20339854/102025093-8436f300-3d4a-11eb-8003-15f5d3c0aefa.png)

**Platform information:**
 - Browser
   - [Chrome] I'm browsing on my laptop using

**Comment by acrellin** [comment]
@yaoyuhan Thanks for bringing the issue to our attention. However, we need more information from you in order to determine exactly what is going on. Can you please provide the API calls you made to upload the spectra?

**Comment by yaoyuhan** [comment]
Hi -- I used the front-end to upload the spectra. The following is what I did:
- click on "Upload Additional Spectroscopy"
- Choose the file
- Set the MJD and Instrument
- Upload
