### ISSUE TITLE
Time negative photometry points

### ISSUE THREAD

**Issue by rjoebruch** [fritz-marshal/fritz-beta-feedback#77]
Some light curves display photometry points "in the future" on the scanning page. 

**To Reproduce**
1. Go to scanning page
2. Select 27/12/2020 8:30 until 28/12/2020 23:58
3. Select program "Infant Supernovae" 
4. Sort alerts according to "jd_det" in descending order
5. Look for candidate: https://fritz.science/source/ZTF20acyvzbr 

**Expected behavior**
Expecting no negative time. Note that on the object page, this does not appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/45436034/103214982-b3d52600-491a-11eb-8b61-13170bd0a325.png)
see that "Daysago" is negative. 

**Platform information:**
 - Fritz version:  v0.9.dev0+git20201221.76627dd+fritz.84a2d8a 
 - Browser
   - [ x] I'm browsing on a desktop

**Additional context**
Again, note that on the object page, the "negative time" does not appear.

**Comment by dannygoldstein** [comment]
Does refreshing the page fix this?

**Comment by dmitryduev** [comment]
Should be fixed by https://github.com/skyportal/skyportal/pull/1910, closing,
