### ISSUE TITLE
Allow searching for unclassified transients/ allow multi-choice  

### ISSUE THREAD

**Issue by idoirani** [fritz-marshal/fritz-beta-feedback#78]
When scanning for  various programs, a great filtration would be to allow to search for unclassified transients, or for transient without a specific classification. In this sense I mean a real astrophysical classification and not e.g. a "hosted" classification. A useful implementation of this could be to allow multiple choices in the classification menu, and to include "no classification" as an option as well. 

Keep up the good work!
Ido

**Comment by dmitryduev** [comment]
@guynir42 would you mind spelling out your thoughts on this please?

**Comment by guynir42** [comment]
I think the way to do this is to provide two columns, each one containing all the available classifications (or, if there are too many, you could just put two lists where you can enter classifications as free-text into each column). 
One column would be "filter only sources that HAVE this classification" and the other column "filter only sources that DONT HAVE this classification". This way you could mark all the astrophysical classifications in the DONT HAVE column and get all the "unclassified" ones. 

I ideally this would also come with some way to quickly pull up each user's last used classification filtering list (or few configurations or something).

**Comment by guynir42** [comment]
Closed by SP #2773
