### ISSUE TITLE
Developer Guidelines documentation error

### ISSUE THREAD

**Issue by scizen9** [fritz-marshal/fritz-beta-feedback#79]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
The command "git remote add upstream git@github.com:fritz/fritz" is in error.  It should read "git remote add upstream git@github.com:fritz-marshal/fritz".

**To Reproduce**
Go to: https://docs.fritz.science/developer.html
Error can be seen in "How to contribute" instructions

**Expected behavior**
See bug description above.

**Platform information:**
 - Fritz version:  v0.9.dev0+git20201221.76627dd+fritz.84a2d8a.
 - Browser
   - [x] I'm browsing on a desktop
   - [ ] I'm browsing on my phone

**Additional context**
None.

**Comment by stefanv** [comment]
Good catch @scizen9!  Do you mind filing a pull request to fix that?

**Comment by acrellin** [comment]
Addressed by  https://github.com/fritz-marshal/fritz/pull/144
