### ISSUE TITLE
Sorting of spectra

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#81]
Hi,

This is from the object page of https://fritz.science/source/ZTF21aabpnlm.

Several spectra were obtained but uploaded in random order. The ranking in the legend is according to the upload date, not date-obs (see picture).

The expected behaviour is that the spectra are always sorted according to the date-obs.

![bug_report_sort according to time](https://user-images.githubusercontent.com/11585543/104589767-a7ff9880-566a-11eb-9581-2e7fa5a9318b.png)

**Comment by scizen9** [comment]
Fixed with [PR#1674](https://github.com/skyportal/skyportal/pull/1674)
