### ISSUE TITLE
Annotating spectra

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#82]
Hi,

**Usage / behavior**
It should be possible to annotate and attach files to spectra, e.g., lines are particularly narrow or wide or spectrum shows line X. This helps people to see immediately what is peculiar about a certain spectrum. People can easily overlook critical information if such comments or files are only shown only in the "Comments" section. These comments should also appear in the 'Comments' box.

**Additional context**
See screenshots

![Screenshot 2021-01-14 at 13 25 09](https://user-images.githubusercontent.com/11585543/104590681-f497a380-566b-11eb-82c2-f8545f116b2b.png)

![Screenshot 2021-01-14 at 13 22 12](https://user-images.githubusercontent.com/11585543/104590597-dc278900-566b-11eb-9ca5-7320d372c008.png)

**Comment by guynir42** [comment]
Closed by #2161 and #1841
