### ISSUE TITLE
Unable to See Filter on Fritz

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#86]
I am currently unable to see the filter for any program (i.e CLU, RCF...). The filter will not load and says that it `"Failed to Fetch Data from Kowalski"`

**To Reproduce**
1. Go to the Groups page
2. Click on Census of the Local Universe Caltech
3. Scroll down to Alert Streams and Filters
4. Click on "clu" filter
5. See the error message

**Expected behavior**
We used to be able to see the most recent version of the filter being used.

**Screenshots**
<img width="1430" alt="frtizphoto" src="https://user-images.githubusercontent.com/22720676/108244068-c4389e80-711c-11eb-98c0-6da2527945a6.png">

**Platform information:**
 - Fritz version:  `v0.9.dev0+git20210209.5f61676+fritz.1da5f9f`
 - Browser
   - [x] I'm browsing on a desktop

Thank you! 🚀

**Comment by dmitryduev** [comment]
Yeah, sorry about that @AndyTza. We refactored the Kowalski side of filtering, but the corresponding PR on Frtiz has not been merged yet (https://github.com/fritz-marshal/fritz/pull/153), working on that.

**Comment by dmitryduev** [comment]
This has been fixed, merged, and deployed, so closing. @AndyTza lmk if it works as expected.
