### ISSUE TITLE
Further survey buttons don't work

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#9]
Hi,

The following buttons also don't work:
- FIRST (not linked)
- CRTS (not linked)
- Variable Marshal (Search)  (not linked)

There is a problem with the Java for
- SkyView
- IRSA/WISE 

PyMP and LCOGT are incorrectly linked.
IPAC is spinning and spinning but shows no result.

Cheers,

Steve

**Comment by dannygoldstein** [comment]
Fixed in skyportal/skyportal#992
