### ISSUE TITLE
Legend in photometry plot truncates the size of the light curve figure.

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#91]
Hi,

Example: https://fritz.science/source/ZTF21aaoiaar

Problem: The legend determines the size of the plot. The legend is too long and should only show vital information.

Cheers,

Steve
![Screenshot 2021-03-19 at 10 18 42](https://user-images.githubusercontent.com/11585543/111758430-cec19180-889c-11eb-99a8-fb254868b347.png)

**Comment by scizen9** [comment]
This can probably be fixed by using the bokeh figure variable frame_width, instead of just width.

**Comment by steveschulze** [comment]
Great!

Sometimes, the legends contain also information that is not relevant at all. For instance, it’s not relevant to know which LCOGT telescope was used.

Cheers,

Steve

From: Don Neill ***@***.***>
Reply to: fritz-marshal/fritz-beta-feedback ***@***.***>
Date: Sunday, 21. March 2021 at 18:09
To: fritz-marshal/fritz-beta-feedback ***@***.***>
Cc: Steve Schulze ***@***.***>, Author ***@***.***>
Subject: Re: [fritz-marshal/fritz-beta-feedback] Legend in photometry plot truncates the size of the light curve figure. (#91)


This can probably be fixed by using the bokeh figure variable frame_width, instead of just width.
