### ISSUE TITLE
Missing filters for instruments. Users must be able to add them.

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#93]
Hi,

Several instruments have pre-configured filters, e.g., Bessel filters for NOT/ALFOSC. We observed with ALFOSC but used SDSS filters. How can we upload such observations to Fritz?

It is very important that users can modify existing instrument configurations and modify those if needed, or that there is a dedicated contact person who can make these changes on short notice. 

Cheers,

Steve

**Comment by acrellin** [comment]
I have now added the SDSS filters to the ALFOSC instrument
