### ISSUE TITLE
Source search menu anomaly

### ISSUE THREAD

**Issue by scizen9** [fritz-marshal/fritz-beta-feedback#94]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
After selecting a source and it fully loading it's page, when I scroll, a list of unrelated sources appears below the search box.

**To Reproduce**
1. Type a partial search string into source search box in left-hand panel
2. Select source to display source page
3.  Use scroll bar until anomalous list appears

**Expected behavior**
Once source is display, search bar should not offer unrelated source as a drop-down menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/6845428/113425086-1dcff200-9386-11eb-8b4a-f754a4d567a6.png)

**Platform information:**
 - Fritz version:  v0.9.dev0+git20210325.d246094+fritz.268a3a2. 
 - Browser
   - [X] I'm browsing on a desktop
   - [ ] I'm browsing on my phone

**Additional context**
I've seen this for quite a while.  This is not recent behaviour.  It is fleeting and I was unable to get a screenshot until now.

**Comment by dmitryduev** [comment]
@scizen9 could this be closed now?

**Comment by scizen9** [comment]
Recent updates appear to have fixed this.
