### ISSUE TITLE
Toggle on/off button for light curve and spec plots

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#96]
Hi,

For long spectroscopic or extensive photometric follow-up campaigns, it is time-consuming to toggle on/off certain data sets.

Desired behaviour: A button that toggles on/off everything. Screenshots are attached.

![Screenshot 2021-04-03 at 13 25 40](https://user-images.githubusercontent.com/11585543/113477142-3b818200-9480-11eb-86c6-84d5566ab89d.png)
![Screenshot 2021-04-03 at 13 25 03](https://user-images.githubusercontent.com/11585543/113477143-3c1a1880-9480-11eb-9a58-2651c455e711.png)

**Comment by scizen9** [comment]
This being addressed by the bokeh project in their [Issue#8841](https://github.com/bokeh/bokeh/issues/8841).  Once these other modes for "click_policy" are implemented, we can adopt them to fix this.

**Comment by guynir42** [comment]
@mcoughlin I think you guys were working on this, right? What's the status?

**Comment by mcoughlin** [comment]
Jada dealt with this.
