### ISSUE TITLE
Need vertical size adjustment for phot, spec plots when legend overfills current frame

### ISSUE THREAD

**Issue by scizen9** [fritz-marshal/fritz-beta-feedback#97]
Please fill out relevant sections below; remove those that are unused.

**Feature Summary**
If there are many sources of photometry, or many spectra, the legend extends beyond the lower limit of the frame.  This should be tested for and a vertical scroll bar added if required.

**Usage / behavior**
Should count number of photometry sources, or number of spectra and add vertical scroll bar if it exceeds the number that would extend the legend beyond the frame.

**Additional context**
Here is an example for spectra:
![image](https://user-images.githubusercontent.com/6845428/114308415-bc500780-9a98-11eb-8448-f1c8297ce5a4.png)

**Comment by scizen9** [comment]
here's the fritz link for this example [ZTF20acphdcg](https://fritz.science/source/ZTF20acphdcg)

**Comment by scizen9** [comment]
[PR#1966](https://github.com/skyportal/skyportal/pull/1966) should address this.

**Comment by kmshin1397** [comment]
Closing as issue has been addressed.
