### ISSUE TITLE
alert aux data empty for /api/alerts/ztf/<ZTFNAME>/aux

### ISSUE THREAD

**Issue by scizen9** [fritz-marshal/fritz-beta-feedback#98]
**Describe the bug**
A get from /api/alerts/ztf/<ZTFNAME>/aux returns an empty "data" dictionary.

**To Reproduce**
1. Go to https://fritz.science/api/alerts/ztf/ZTF21aaskyvp/aux
2. See error

**Expected behavior**
Expected a full alert dictionary of aux information, specifically including TNS cross_matches.

**Screenshots**
`{
  "status": "success",
  "data": [],
  "version": "0.9.dev0+git20210419.e0c871c+fritz.156f4b5"
}`

**Platform information:**
 - Fritz version:  v0.9.dev0+git20210419.e0c871c+fritz.156f4b5.
 - Browser
   - [x] I'm browsing on a desktop
   - [ ] I'm browsing on my phone

**Additional context**
This was working previously.  The example target is not particularly new and was verified to be on TNS.

**Comment by acrellin** [comment]
Endpoint has been moved to https://docs.fritz.science/api.html#tag/alerts/paths/~1api~1alerts_aux~1object_id/get
