### ISSUE TITLE
Filter sources based on classification ("Sitewide taxonomy: Ia") stopped working

### ISSUE THREAD

**Issue by joeljoh** [fritz-marshal/fritz-beta-feedback#99]
Previously, I was able to filter sources based on Classification (and then further sort that table). Since April 25 (approximately), this does not work if you choose classification = 'Sitewide taxonomy: Ia'.

**To Reproduce**
1. Go to 'sources'
2. Click "Filter table"
3. Scroll down to 'Sitewide taxonomy: Ia' in Classifications
4. Source table remains un-filtered and un-responsive (note: this works for any other classification, e.g. "Sitewide classification: Ibn")

**Expected behavior**
Sortable source table only showing saved Ia supernovae. This worked as expected prior to ~April 25 (see note below)

**Screenshots**
<img width="1264" alt="Screenshot 2021-04-30 at 11 42 54" src="https://user-images.githubusercontent.com/71870267/116679983-73121a00-a9ab-11eb-83fe-443dafed1ee3.png">

**Platform information:**
 - Fritz version:  (find this in the [About](https://fritz.science/about) page)
 - Browser: Chrome
   - [x] I'm browsing on a desktop
   - [x] I'm browsing on my phone

**Additional context**
One lead for the troubleshooting might be that a large number (3000) of Ia supernovae were batch-saved form the Growth marshal to fritz, to groupid=55 around April 25-27 with classification P set to "null" (see e.g. https://fritz.science/source/ZTF18aaajrso). Maybe this is the root of the problem?

**Comment by acrellin** [comment]
Unable to reproduce (see screenshot showing filtered table): 
![image](https://user-images.githubusercontent.com/7230285/116727011-dfcfe900-a998-11eb-9264-5e12e4d03fce.png)

**Comment by acrellin** [comment]
Please try again, and wait a few seconds after submitting the query
